### ISSUE TITLE
Unhandled exception during execution

### ISSUE THREAD

**Issue by Parappapper0** [gglobensky/ModpackUpdateManager#2]
While trying to transfer mods from 1.19.4 to 1.16.4 the program, after downloading about a quarter of the mods gave an exception saying
```Tomlyn.TomlException: (20,14) : error : Invalid newline in a string
(21,94) : error : Invalid newline in a string
(22,1) : error : Invalid newline in a string
(23,1) : error : Invalid newline in a string
(24,1) : error : Invalid newline in a string

   at Tomlyn.Toml.ToModel[T](String text, String sourcePath, TomlModelOptions options)
   at ModpackUpdateManager.Components.Core.ModDataAccessor.ReadJarModTomlFileContent(String path) in C:\Users\Guillaume Globensky\source\repos\ModpackUpdateManager\ModpackUpdateManager\ModpackUpdateManager\Components\Core\ModDataAccessor.cs:line 268
   at ModpackUpdateManager.Components.Core.ModDataAccessor.GetModData(String path, String fileName) in C:\Users\Guillaume Globensky\source\repos\ModpackUpdateManager\ModpackUpdateManager\ModpackUpdateManager\Components\Core\ModDataAccessor.cs:line 65
   at ModpackUpdateManager.Components.Core.ModDataAccessor.GetAllModData(String path, Action`1 onModTomlFileNotFound) in C:\Users\Guillaume Globensky\source\repos\ModpackUpdateManager\ModpackUpdateManager\ModpackUpdateManager\Components\Core\ModDataAccessor.cs:line 47
   at ModpackUpdateManager.Components.Core.ModDataAccessor.SkipExisting(Action onSkipExisting) in C:\Users\Guillaume Globensky\source\repos\ModpackUpdateManager\ModpackUpdateManager\ModpackUpdateManager\Components\Core\ModDataAccessor.cs:line 228
   at ModpackUpdateManager.Components.Core.ModDataAccessor..ctor(Dictionary`2 gameFlavorIds, List`1 _searchTermBlacklist, Action`1 onSourceModFileNotFound, Action onSkippingExisting) in C:\Users\Guillaume Globensky\source\repos\ModpackUpdateManager\ModpackUpdateManager\ModpackUpdateManager\Components\Core\ModDataAccessor.cs:line 36
   at ModpackUpdateManager.Components.Core.ModOperationManager..ctor(String _reportModPath, String getModSearchResultFullPath, String _invalidDownloadsFolderName, String _dependenciesModPath, Dictionary`2 _gameVersionIds, Dictionary`2 _gameFlavorIds, List`1 searchTermBlacklist, UserMessaging _userMessaging) in C:\Users\Guillaume Globensky\source\repos\ModpackUpdateManager\ModpackUpdateManager\ModpackUpdateManager\Components\Core\ModOperationManager.cs:line 58
   at ModpackUpdateManager.Components.InitContainer.CreateMainForm(Form2 form2) in C:\Users\Guillaume Globensky\source\repos\ModpackUpdateManager\ModpackUpdateManager\ModpackUpdateManager\Components\InitContainer.cs:line 96
   at ModpackUpdateManager.Form2.btn_Accept_Click(Object sender, EventArgs e) in C:\Users\Guillaume Globensky\source\repos\ModpackUpdateManager\ModpackUpdateManager\ModpackUpdateManager\Form2.cs:line 105
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
Trying to press continue the first time it threw the exception made it possible to continue only in manual mode, while after restarting the program cannot be used anymore

**Comment by gglobensky** [comment]
Can you provide me with the logs files that are located in the logs folder?
My guess is that a mod has an unexpected mods.toml file structure.
So if you remember the mod that caused the crash it would be even better.

There doesn't seem to have a standard in how they are made so sometimes I have to tweak the code.

**Comment by Parappapper0** [comment]
All of the log files seem to be empty, and from the exception message I can't find the mod causing this. I tried removing the mod that was last updated and the one which would've been the next but that didn't work. I can send the whole exception details if you want.

**Comment by gglobensky** [comment]
If possible, can you provide me your mod list?
You can type in the command /mod list while in game to get it.

Can you also confirm that you were using the latest build of the manager?

**Comment by Parappapper0** [comment]
So, I think the problem is in the "Skip already existing" part, because after manually moving the destination folder mods and removing the source folder mods associated and not ticking it it worked fine again, but idk why

**Comment by gglobensky** [comment]
Okay thanks, I'll have a look at that when I get some time!
I'm glad it worked for you in the end.
